spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # or create-drop for a fresh schema each run
    show-sql: true
    defer-datasource-initialization: true   # ? run data.sql AFTER Hibernate creates tables
  sql:
    init:
      mode: always            # ensure data.sql runs
  h2:
    console:
      enabled: true
  ai:
    mcp:
      server:
        protocol: STREAMABLE           # use Streamable-HTTP transport
        name: orders-mcp-server        # server name advertised to clients
        version: 1.0.0                 # your service version
        annotation-scanner:
          enabled: true
        capabilities:
          tools: true          # ? make sure this is true
        streamable-http:
          mcp-endpoint: /mcp           # endpoint clients will call
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health        # only expose the health endpoint
  endpoint:
    health:
      probes:
        enabled: true          # enables /health/liveness and /health/readiness

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai.model.tool: DEBUG
